[theme]
primaryColor = "#eca400"  # Neon Aqua for highlights & buttons (futuristic feel)
backgroundColor = "#006992"  # Deep Navy Blue for a modern dark mode
secondaryBackgroundColor = "#001d4a"  # Darker Blue for sidebar & panels
textColor = "#ffffff"  # Soft White for readability without harsh contrast
