[theme]
primaryColor = "#eca400"  # Golden Yellow for a warm accent
backgroundColor = "#006992"  # Deep Blue for the main background
secondaryBackgroundColor = "#001d4a"  # Dark Blue for secondary elements
textColor = "#ffffff"  # Soft White for readability without harsh contrast
font = "sans serif"  # Clean and modern font